[[main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 1

[[main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    weight = 2

[[main]]
    identifier = "team"
    name = "Team"
    url = "/team"
    weight = 3

[[main]]
    identifier = "highlighted_works"
    name = "Highlighted Works"
    url = "/highlighted_works"
    weight = 4

[[main]]
    identifier = "recent_publications"
    name = "Recent Publications"
    url = "/recent_publications"
    weight = 5

[[main]]
    identifier = "software"
    name = "Software"
    url = "/software"
    weight = 6
    
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/muexly"
    weight = 1

[[social]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 2